name: "Install Inno Setup"

description: "Install Inno Setup"

inputs:
  version:
    description: "Version of Inno Setup to install (e.g. 6.7.1)"
    default: "6.7.1"

runs:
  using: node24
  main: dist/index.cjs
