name: "Install Inno Setup"

description: "Install Inno Setup"

inputs:
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Inno Setup
      id: cache-innosetup
      uses: actions/cache@v4
      with:
        path: |
          innosetup-${{ inputs.version }}
        key: ${{ runner.os }}-innosetup-${{ inputs.version }}

    - name: Install Inno Setup
      if: steps.cache-innosetup.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://files.jrsoftware.org/is/6/innosetup-${{ inputs.version }}.exe -OutFile innosetup-${{ inputs.version }}.exe
        Start-Process -FilePath ".\innosetup-${{ inputs.version }}.exe" -ArgumentList "/VERYSILENT", "/CURRENTUSER", "/DIR=innosetup-${{ inputs.version }}" -Wait
        Remove-Item .\innosetup-${{ inputs.version }}.exe
        Add-Content $env:GITHUB_PATH "$(Get-Location)\innosetup-${{ inputs.version }}"

    - name: Add Inno Setup to path
      shell: pwsh
      run: |
        Add-Content $env:GITHUB_PATH "$(Get-Location)\innosetup-${{ inputs.version }}"
