name: "Install Ninja"

description: "Install Ninja"

inputs:
  version:
    description: "Version of Ninja to install (e.g. 1.13.2)"
    default: "1.13.2"

runs:
  using: node24
  main: dist/index.cjs
