name: "Install Python"
description: "Install Python & uv"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
