name: 'Upload to Release'
description: 'Upload from artifacts to a tag'
inputs:
  tag:
    required: true
  token:
    required: true
  reuse_tag:
    required: true
  create_tag:
    required: true
  release_blurb_file:
    description: "A file in your source tree which is included in the release"
runs:
  using: "composite"
  steps:
    - name: Show Arguments
      shell: bash
      run: |
        echo "Arguments are: "
        echo " tag : ${{ inputs.tag }}"
        echo " reuse_tag : ${{ inputs.reuse_tag }}"
        echo " create_tag : ${{ inputs.create_tag }}"

    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Show Installer Directory
      shell: bash
      run: |
        ls -R artifacts

    - name: Make MD5Sum
      shell: bash
      run: |
        find artifacts -type f -exec md5sum '{}' \; > artifact_md5sum.txt

    - name: Checkout code for release notes
      uses: actions/checkout@v4
      with:
        path: source
        fetch-depth: 5

    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      if: ${{ inputs.reuse_tag == 'true'}}
      with:
        token: ${{ inputs.token }}
        tag: ${{ inputs.tag }}
        assets: '*'
        fail-if-no-assets: false

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: ${{ inputs.create_tag == 'true'}}
      with:
        tag_name: ${{ inputs.tag }}
        name: Release ${{ inputs.tag }}
        body: |
          ${{ env.GITHUB_REPOSITORY_NAME }} Release ${{ inputs.tag }}
        draft: false
        prerelease: false

    - name: Update Release Notes
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        cd source
        touch rn.md
        if test -f "${{ inputs.release_blurb_file }}"; then
          cat "${{ inputs.release_blurb_file }}" >> rn.md
        fi
        echo "Release updated " `date` >> rn.md
        echo >> rn.md
        git log -5 --pretty=format:'- [%h](${{ github.server_url }}/${{ github.repository }}/commit/%H) : %s'  >> rn.md

        gh release edit --notes-file rn.md ${{ inputs.tag }}


    - name: Upload release assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.token }}
        file: artifacts/**/**/**
        tag: ${{ inputs.tag }}
        file_glob: true

    - name: Upload release assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.token }}
        file: artifact_md5sum.txt
        tag: ${{ inputs.tag }}
        file_glob: false

    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      if: ${{ inputs.reuse_tag == 'true' }}
      with:
        tag_name: ${{ inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
