name: 'Upload to Nightly'
description: 'Upload from artifacts to a tag which pre-exists'
inputs:
  tag:
    required: true
  token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Show Installer Directory
      shell: bash
      run: |
        ls -R artifacts
    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ inputs.token }}
        tag: ${{ inputs.tag }}
        assets: '*'
    - name: Upload release assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.token }}
        file: artifacts/**/**/**
        tag: Nightly
        file_glob: true
    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: Nightly
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
