name: "uv tool"

description: "Add a Python tool with uv"

inputs:
  tool:
    description: "Tool name"
    required: true
  version:
    description: "Tool version"
    required: true

runs:
  using: node24
  main: dist/index.cjs
