name: 'Publish Doxygen'
description: 'Run and Publish Doxygen'
inputs:
  token:
    description: "Access token to get to sst-docs"
    required: true
  destination:
    required: true
    description: "Subdir destination. Probably just the repo name"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: source

    - name: Checkout web
      uses: actions/checkout@v2
      with:
        path: web
        repository: surge-synthesizer/sst-docs
        token: ${{ inputs.token }}


    - name: "Bail on Purpose"
      shell: bash
      run: |
        exit 123
