name: 'Publish Doxygen'
description: 'Run and Publish Doxygen'
inputs:
  token:
    description: "Access token to get to sst-docs"
    required: true
  destination:
    required: true
    description: "Subdir destination. Probably just the repo name"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: source

    - name: Checkout web
      uses: actions/checkout@v2
      with:
        path: web
        repository: surge-synthesizer/sst-docs
        token: ${{ inputs.token }}

    - name: Run Doxygen
      shell: bash
      run: |
        sudo apt-get install doxygen graphviz
        pushd source
        doxygen doxygen/Doxyfile
        ls doxy-out
        pushd doxy-out
        tar cf - . | (cd ../../web/docs/${{ inputs.destination }} && tar xf -)
        popd
        popd
        cd web
        git status
        
        git config user.email "paul@baconpaul.org"
        git config user.name "baconpaul"
        
        git add .
        git commit -m "Update doxygen for ${{ inputs.destination }} from github action"
        git push origin main
