name: 'Publish Doxygen'
description: 'Run and Publish Doxygen'
inputs:
  token:
    description: "Access token to get to sst-docs"
    required: true
  destination:
    required: true
    description: "Subdir destination. Probably just the repo name"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: source

    - name: Checkout web
      uses: actions/checkout@v2
      with:
        path: web
        repository: surge-synthesizer/sst-docs
        token: ${{ inputs.token }}

    - name: Run Doxygen
      shell: bash
      run: |
        sudo apt-get install doxygen graphviz
        pushd source
        doxygen doxygen/Doxyfile
        ls doxy-out
        tar cf - . | (cd ../web/docs/${{ inputs.destination }} && tar xf -)
        popd
        cd web
        git status
      

    - name: "Bail on Purpose"
      shell: bash
      run: |
        exit 123
