name: 'Setup Image for JUCE Build'
description: 'Apt Get, XCode Select, things like that'
inputs:
  webhook:
    required: true
    description: "The webhook for the place to post"
  tag:  # id of input
    required: true
    desciption: "The tag for this release"
  title:
    required: true
    description: "First bold line. Probably name of thing"
  subtitle:
    required: false
    description: "Second unbold line. Whatever you want"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
      
    - name: Generate JSON
      shell: bash
      run: |
        echo "**${{ inputs.title }}**" > tmpfile.txt
        
        if test -z "${{ inputs.subtitle }}"; then
          echo "${{ inputs.subtitle }}" >> tmpfile.txt
        fi
        
        git log -1 --pretty=format:'`%h : %s - %an`' >> tmpfile.txt
        echo "" >> tmpfile.txt
        echo "<${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.tag }}>" >> tmpfile.txt
        
        echo "----"
        cat tmpfile.txt
        echo "----"
        
        awk '{printf "%s\\n", $0}' tmpfile.txt > tmpfile.sline
        awk '{printf "{ \"content\": \"%s\" }", $0}' tmpfile.sline > tmpfile.json
        
        cat tmpfile.json

    - name: Post to discord
      shell: bash
      run: |
        curl -i -H "Accept: application/json" \
                  -H "Content-Type:application/json" \
                  -X POST \
                  -d @tmpfile.json \
                  ${{ inputs.webhook }}

        
        
        
