name: 'Clang Format Check'
description: 'Apt Get, XCode Select, things like that'
inputs:
  path:
    required: true
runs:
  using: "composite"
  steps:
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '17'
        check-path: ${{ inputs.path }}
