name: 'Clang Format Check'
description: 'Apt Get, XCode Select, things like that'
inputs:
  path:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install clang-format
      shell: bash
      run: pip3 install clang-format==21.1.5

    - name: Run clang format
      shell: bash
      run: |
        echo "Running clang-format on ${{ inputs.path }}" 
        clang-format --version 
        pushd ${{ inputs.path }}
        find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|c\|m\|mm\)' -exec clang-format -style=file --dry-run --Werror {} +