name: "Clang Format Check"
description: "Clang Format Check"
inputs:
  path:
    description: "Path to check with clang-format"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: surge-synthesizer/sst-githubactions/install-python@main

    - name: Install clang-format
      uses: surge-synthesizer/sst-githubactions/install-clang-format@main

    - name: Run clang format
      shell: bash
      run: |
        echo "Running clang-format on ${{ inputs.path }}"
        clang-format --version
        pushd ${{ inputs.path }}
        find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|c\|m\|mm\)' -exec clang-format -style=file --dry-run --Werror {} +
